-- MySQL Script generated by MySQL Workbench
-- Sun Mar  1 23:27:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `countries` (
  `id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` INT(11) NOT NULL,
  `alpha2` VARCHAR(255) NOT NULL,
  `alpha3` VARCHAR(255) NOT NULL,
  `name_en_gb` VARCHAR(255) NOT NULL,
  `name_fr_fr` VARCHAR(255) NOT NULL,
  `price` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `regions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regions` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(3) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `regions_code_unique` (`code` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `departments` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `region_code` VARCHAR(255) NOT NULL,
  `code` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `departments_code_unique` (`code` ASC),
  INDEX `departments_region_code_foreign` (`region_code` ASC),
  CONSTRAINT `departments_region_code_foreign`
    FOREIGN KEY (`region_code`)
    REFERENCES `regions` (`code`))
ENGINE = InnoDB
AUTO_INCREMENT = 110
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cities` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `department_code` VARCHAR(255) NOT NULL,
  `insee_code` VARCHAR(255) NOT NULL,
  `zip_code` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `gps_lat` DOUBLE(16,14) NOT NULL,
  `gps_lng` DOUBLE(17,14) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `cities_department_code_foreign` (`department_code` ASC),
  CONSTRAINT `cities_department_code_foreign`
    FOREIGN KEY (`department_code`)
    REFERENCES `departments` (`code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 35854
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `sf_id` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `country_id` SMALLINT(5) UNSIGNED NULL DEFAULT NULL,
  `zip_code_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `role` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC),
  INDEX `fk_users_countries_1_idx` (`country_id` ASC),
  INDEX `fk_users_zip_code_2_idx` (`zip_code_id` ASC),
  CONSTRAINT `fk_users_countries_1_idx`
    FOREIGN KEY (`country_id`)
    REFERENCES `countries` (`id`),
  CONSTRAINT `fk_users_zip_code_2_idx`
    FOREIGN KEY (`zip_code_id`)
    REFERENCES `cities` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ads` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_admin_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `user_pp_id` INT(10) UNSIGNED NOT NULL,
  `is_draft` TINYINT(1) NOT NULL,
  `accept_share_contact_infos` TINYINT(1) NOT NULL DEFAULT '0',
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `about_content` VARCHAR(1000) NULL DEFAULT NULL,
  `about_project_content` VARCHAR(1000) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `iix_ads_user_admin_id` (`user_admin_id` ASC),
  INDEX `ix_ads_user_lead_id` (`user_pp_id` ASC),
  CONSTRAINT `iix_ads_user_admin_id`
    FOREIGN KEY (`user_admin_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `ix_ads_user_lead_id`
    FOREIGN KEY (`user_pp_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `documentables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `documentables` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `document_id` INT(10) UNSIGNED NOT NULL,
  `documentable_id` INT(10) UNSIGNED NOT NULL,
  `documentable_type` VARCHAR(255) NOT NULL COMMENT 'tables référentes : ads et ad_note',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_documentable_1` (`document_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `documents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `documents` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `path` VARCHAR(255) NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `size` INT(11) NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `documents_user_id_foreign` (`user_id` ASC),
  CONSTRAINT `documents_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `land_offer_ads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `land_offer_ads` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `accept_use_zip_code` TINYINT(1) NOT NULL DEFAULT '1',
  `surface` INT(11) NOT NULL,
  `sau_description` VARCHAR(1000) NULL DEFAULT NULL,
  `water_access` TINYINT(1) NULL DEFAULT NULL,
  `ad_id` INT(10) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_land_offer_ads_1_idx` (`ad_id` ASC),
  CONSTRAINT `fk_land_offer_ads_1_idx`
    FOREIGN KEY (`ad_id`)
    REFERENCES `ads` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `land_seek_ads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `land_seek_ads` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `is_bio` TINYINT(1) NULL DEFAULT NULL,
  `experience_farming` TEXT NULL DEFAULT NULL,
  `ad_id` INT(10) UNSIGNED NOT NULL,
  `surface_range_min` INT(11) NULL DEFAULT NULL,
  `surface_range_max` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_land_seek_ads_1_idx` (`ad_id` ASC),
  CONSTRAINT `fk_land_seek_ads_1_idx`
    FOREIGN KEY (`ad_id`)
    REFERENCES `ads` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `locationable_ads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locationable_ads` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ad_id` INT(10) UNSIGNED NOT NULL,
  `locationable_ad_id` INT(10) UNSIGNED NOT NULL,
  `locationable_ad_type` VARCHAR(255) NOT NULL COMMENT 'cette colonne fait référence aux tables ads, researches',
  `radius` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_locationable_ads_1` (`ad_id` ASC),
  INDEX `ix_locationable_ad_1` (`locationable_ad_id` ASC),
  INDEX `ix_locationable_ad_2` (`locationable_ad_type` ASC),
  CONSTRAINT `fk_locationable_ads_1`
    FOREIGN KEY (`ad_id`)
    REFERENCES `ads` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `production_genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `production_genres` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `parent_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_parent_idx` (`parent_id` ASC),
  CONSTRAINT `fk_parent_idx`
    FOREIGN KEY (`parent_id`)
    REFERENCES `production_genres` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `productionable_genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `productionable_genres` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `production_genre_id` INT(10) UNSIGNED NOT NULL,
  `productionable_genre_id` INT(10) UNSIGNED NOT NULL,
  `productionable_genre_type` VARCHAR(255) NOT NULL COMMENT 'Cette colonne liste les modèle qui sont rattaché à un type de production : la table land_seek_ads, land_offer_ads et la table researches.',
  `type` ENUM('actual', 'possible') NOT NULL DEFAULT 'actual',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_productionable_genre_1_idx` (`production_genre_id` ASC),
  INDEX `ix_productionable_genre_2` (`productionable_genre_type` ASC),
  INDEX `ix_productionable_genre_1` (`productionable_genre_id` ASC),
  CONSTRAINT `fk_productionable_genre_1_idx`
    FOREIGN KEY (`production_genre_id`)
    REFERENCES `production_genres` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Table `ad_moderation_locking_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ad_moderation_locking_status` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ad_id` int(10) UNSIGNED NOT NULL,
  `moderating` tinyint(1) NOT NULL DEFAULT 0,
  `user_id` int(10) UNSIGNED NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ad_id` (`ad_id`),
  KEY `user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;